# -*- coding: utf-8 -*-
"""Arts and Advanced Big Data-Park-Week3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F9Wl_wBecXSoardoiLr9AOqO0QSr204a

# Mini Project A — Generative Abstract Poster

For this assignment, I modified the given code to create multiple types of generative posters with different design concepts such as simple and vivid. By adjusting parameters like color palettes, layer numbers, and blob irregularity, I explored various visual styles and compositions. Finally, I added code to save each generated poster as a PNG file, allowing me to document and compare the results of different design concepts.
"""

# Generative Abstract Poster
# Concepts: randomness, lists, loops, functions, matplotlib

import random
import math
import numpy as np
import matplotlib.pyplot as plt

def random_palette(k=5):
    # return k random pastel-like colors
    return [(random.random(), random.random(), random.random()) for _ in range(k)]

def blob(center=(0.5, 0.5), r=0.3, points=200, wobble=0.15):
    # generate a wobbly closed shape
    angles = np.linspace(0, 2*math.pi, points)
    radii = r * (1 + wobble*(np.random.rand(points)-0.5))
    x = center[0] + radii * np.cos(angles)
    y = center[1] + radii * np.sin(angles)
    return x, y

random.seed()  # different art each run
plt.figure(figsize=(7,10))
plt.axis('off')

# background
plt.gca().set_facecolor((0.98,0.98,0.97))

palette = random_palette(6)
n_layers = 8
for i in range(n_layers):
    cx, cy = random.random(), random.random()
    rr = random.uniform(0.15, 0.45)
    x, y = blob(center=(cx, cy), r=rr, wobble=random.uniform(0.05,0.25))
    color = random.choice(palette)
    alpha = random.uniform(0.25, 0.6)
    plt.fill(x, y, color=color, alpha=alpha, edgecolor=(0,0,0,0))

# simple typographic label
plt.text(0.05, 0.95, "Generative Poster", fontsize=18, weight='bold', transform=plt.gca().transAxes)
plt.text(0.05, 0.91, "Week 2 • Arts & Advanced Big Data", fontsize=11, transform=plt.gca().transAxes)

plt.xlim(0,1); plt.ylim(0,1)
plt.show()

"""# Task1"""

# Import required libraries
import random       # for random numbers and choices
import math         # for math functions like pi, cos, sin
import numpy as np  # for efficient array operations
import matplotlib.pyplot as plt  # for plotting shapes

def random_palette(k=5):
    """
    Generate a list of k random colors.
    Colors are RGB tuples with values between 0 and 1.
    """
    return [(random.random(), random.random(), random.random()) for _ in range(k)]

def blob(center=(0.5, 0.5), r=0.3, points=200, wobble=0.15):
    """
    Create a wobbly blob shape around a center point.
    center: (x,y) position of the blob center
    r: base radius of the blob
    points: number of points to define the shape
    wobble: how irregular the radius is
    """
    angles = np.linspace(0, 2*math.pi, points)  # evenly spaced angles around a circle
    radii = r * (1 + wobble*(np.random.rand(points)-0.5))  # base radius + random variation
    x = center[0] + radii * np.cos(angles)  # x-coordinates of blob edge
    y = center[1] + radii * np.sin(angles)  # y-coordinates of blob edge
    return x, y  # return arrays of x and y coordinates

random.seed()  # re-seed random generator so each run gives different results
plt.figure(figsize=(7,10))  # create a new figure with specified size
plt.axis('off')  # hide axis lines and labels for a clean look

# set background color of the plot area to a near-white shade
plt.gca().set_facecolor((0.98,0.98,0.97))

palette = random_palette(6)  # generate 6 random colors to choose from
n_layers = 8  # number of blob layers to draw
for i in range(n_layers):
    cx, cy = random.random(), random.random()  # random center for each blob
    rr = random.uniform(0.15, 0.45)            # random base radius for the blob
    x, y = blob(center=(cx, cy), r=rr, wobble=random.uniform(0.05,0.25))
    # create blob shape with random irregularity
    color = random.choice(palette)  # randomly pick a color from the palette
    alpha = random.uniform(0.25, 0.6)  # set random transparency for each blob
    plt.fill(x, y, color=color, alpha=alpha, edgecolor=(0,0,0,0))
    # draw the blob as a filled shape without visible edges

# add title text to the poster at top-left corner
plt.text(0.05, 0.95, "Generative Poster", fontsize=18, weight='bold', transform=plt.gca().transAxes)
# add subtitle text slightly below the title
plt.text(0.05, 0.91, "Week 2 • Arts & Advanced Big Data", fontsize=11, transform=plt.gca().transAxes)

plt.xlim(0,1); plt.ylim(0,1)  # keep drawing area within 0–1 normalized coordinates
plt.show()  # display the final figure

"""# Task2 - Simple&Tidy"""

#n_layers = 3 (less blobs)
#wobble (0.01~0.05) → almost round
#radius (0.1~0.25) → smaller

#This change made the shapes look more static

import random, math
import numpy as np
import matplotlib.pyplot as plt

def random_palette(k=5):
    return [(random.random(), random.random(), random.random()) for _ in range(k)]

def blob(center=(0.5, 0.5), r=0.3, points=200, wobble=0.15):
    angles = np.linspace(0, 2*math.pi, points)
    radii = r * (1 + wobble*(np.random.rand(points)-0.5))
    x = center[0] + radii * np.cos(angles)
    y = center[1] + radii * np.sin(angles)
    return x, y

random.seed()
plt.figure(figsize=(7,10))
plt.axis('off')
plt.gca().set_facecolor((0.98,0.98,0.97))

palette = random_palette(6)
n_layers = 3  # fewer blobs
for i in range(n_layers):
    cx, cy = random.random(), random.random()
    rr = random.uniform(0.1, 0.25)  # smaller radius
    x, y = blob(center=(cx, cy), r=rr, wobble=random.uniform(0.01,0.05))  # tiny wobble
    color = random.choice(palette)
    alpha = random.uniform(0.25, 0.6)
    plt.fill(x, y, color=color, alpha=alpha, edgecolor=(0,0,0,0))

plt.text(0.05, 0.95, "Generative Poster A", fontsize=18, weight='bold', transform=plt.gca().transAxes)
plt.text(0.05, 0.91, "Few Layers • Small Wobble", fontsize=11, transform=plt.gca().transAxes)
plt.xlim(0,1); plt.ylim(0,1)
plt.show()

"""# Task2 - Splendid&Complex"""

#n_layers = 20 (many blobs)
#wobble (0.3~0.5) → extremely wavey
#radius (0.3~0.6) → bigger

#This change made the shapes look more extreme and passionate

import random, math
import numpy as np
import matplotlib.pyplot as plt

def random_palette(k=5):
    return [(random.random(), random.random(), random.random()) for _ in range(k)]

def blob(center=(0.5, 0.5), r=0.3, points=200, wobble=0.15):
    angles = np.linspace(0, 2*math.pi, points)
    radii = r * (1 + wobble*(np.random.rand(points)-0.5))
    x = center[0] + radii * np.cos(angles)
    y = center[1] + radii * np.sin(angles)
    return x, y

random.seed()
plt.figure(figsize=(7,10))
plt.axis('off')
plt.gca().set_facecolor((0.98,0.98,0.97))

palette = random_palette(6)
n_layers = 20  # many blobs
for i in range(n_layers):
    cx, cy = random.random(), random.random()
    rr = random.uniform(0.3, 0.6)  # larger radius
    x, y = blob(center=(cx, cy), r=rr, wobble=random.uniform(0.3,0.5))  # strong wobble
    color = random.choice(palette)
    alpha = random.uniform(0.25, 0.6)
    plt.fill(x, y, color=color, alpha=alpha, edgecolor=(0,0,0,0))

plt.text(0.05, 0.95, "Generative Poster B", fontsize=18, weight='bold', transform=plt.gca().transAxes)
plt.text(0.05, 0.91, "Many Layers • Large Wobble", fontsize=11, transform=plt.gca().transAxes)
plt.xlim(0,1); plt.ylim(0,1)
plt.show()

"""# Task3 - Pastel colors only"""

import random, math
import numpy as np
import matplotlib.pyplot as plt

def pastel_palette(k=6):
    """
    Generate k pastel colors (soft and bright).
    We'll bias RGB values towards high (light) and desaturate.
    """
    colors = []
    for _ in range(k):
        r = random.uniform(0.7, 1.0)  # high red
        g = random.uniform(0.7, 1.0)  # high green
        b = random.uniform(0.7, 1.0)  # high blue
        # 살짝 랜덤으로 섞어서 핑크/연보라/민트/연노랑 느낌 만들기
        colors.append((r, g, b))
    return colors

def blob(center=(0.5, 0.5), r=0.3, points=200, wobble=0.15):
    angles = np.linspace(0, 2*math.pi, points)
    radii = r * (1 + wobble*(np.random.rand(points)-0.5))
    x = center[0] + radii * np.cos(angles)
    y = center[1] + radii * np.sin(angles)
    return x, y

random.seed()
plt.figure(figsize=(7,10))
plt.axis('off')
plt.gca().set_facecolor((1.0, 0.98, 0.99))  # 연한 핑크빛 배경

palette = pastel_palette(8)  # pastel colors
n_layers = 12  # 적당히 많은 레이어
for i in range(n_layers):
    cx, cy = random.random(), random.random()
    rr = random.uniform(0.15, 0.35)  # 중간 크기
    x, y = blob(center=(cx, cy), r=rr, wobble=random.uniform(0.05,0.2))  # 약간의 울퉁불퉁
    color = random.choice(palette)
    alpha = random.uniform(0.4, 0.7)
    plt.fill(x, y, color=color, alpha=alpha, edgecolor=(0,0,0,0))

# 소녀스러운 폰트 색상
plt.text(0.05, 0.95, "Generative Poster D", fontsize=18, weight='bold', transform=plt.gca().transAxes, color=(0.6,0.2,0.5))
plt.text(0.05, 0.91, "Pastel & Girly Mood", fontsize=11, transform=plt.gca().transAxes, color=(0.7,0.3,0.6))
plt.xlim(0,1); plt.ylim(0,1)
plt.show()

"""# Task3 - High-contrast vivid colors"""

import random, math
import numpy as np
import matplotlib.pyplot as plt

def limited_vivid_palette():
    """
    Limited vivid palette: neon lime + vivid pink + black
    """
    return [
        (0.0, 1.0, 0.0),     # neon lime
        (1.0, 0.0, 0.6),     # vivid pink
        (0.05, 0.05, 0.05)   # almost black
    ]

def blob(center=(0.5, 0.5), r=0.3, points=200, wobble=0.15):
    angles = np.linspace(0, 2*math.pi, points)
    radii = r * (1 + wobble*(np.random.rand(points)-0.5))
    x = center[0] + radii * np.cos(angles)
    y = center[1] + radii * np.sin(angles)
    return x, y

random.seed()
plt.figure(figsize=(7,10))
plt.axis('off')
plt.gca().set_facecolor((0.0,0.0,0.0))  # black background

palette = limited_vivid_palette()
n_layers = 8  # fewer layers for clean look
for i in range(n_layers):
    cx, cy = random.random(), random.random()
    rr = random.uniform(0.25, 0.5)  # medium radius
    x, y = blob(center=(cx, cy), r=rr, wobble=random.uniform(0.1,0.3))  # moderate wobble
    color = random.choice(palette)
    alpha = random.uniform(0.5, 0.9)
    plt.fill(x, y, color=color, alpha=alpha, edgecolor=(0,0,0,0))

# Text in neon lime
plt.text(0.05, 0.95, "Generative Poster F", fontsize=18, weight='bold', transform=plt.gca().transAxes, color=(0.0,1.0,0.0))
plt.text(0.05, 0.91, "Neon Lime + Black + Pink", fontsize=11, transform=plt.gca().transAxes, color=(1.0,0.0,0.6))
plt.xlim(0,1); plt.ylim(0,1)
plt.show()

"""# Task3 - Monochrome Shades"""

#pallet: green-blue

import random, math
import numpy as np
import matplotlib.pyplot as plt

def green_palette(k=5):
    """
    Generate k greenish colors.
    Hues stay in green range but with varying lightness/saturation.
    """
    colors = []
    for _ in range(k):
        # r을 작게, g를 크게, b는 랜덤하게 섞어 연두~청록 느낌
        r = random.uniform(0.0, 0.3)    # very low red
        g = random.uniform(0.5, 1.0)    # high green
        b = random.uniform(0.3, 0.7)    # medium blue
        colors.append((r, g, b))
    return colors

def blob(center=(0.5, 0.5), r=0.3, points=200, wobble=0.15):
    angles = np.linspace(0, 2*math.pi, points)
    radii = r * (1 + wobble*(np.random.rand(points)-0.5))
    x = center[0] + radii * np.cos(angles)
    y = center[1] + radii * np.sin(angles)
    return x, y

random.seed()
plt.figure(figsize=(7,10))
plt.axis('off')
plt.gca().set_facecolor((0.96,1.0,0.96))  # 약간 연한 연두빛 배경

palette = green_palette(6)  # greenish colors
n_layers = 10  # medium number of blobs
for i in range(n_layers):
    cx, cy = random.random(), random.random()
    rr = random.uniform(0.2, 0.5)  # medium radius
    x, y = blob(center=(cx, cy), r=rr, wobble=random.uniform(0.1,0.3))  # medium wobble
    color = random.choice(palette)
    alpha = random.uniform(0.3, 0.6)
    plt.fill(x, y, color=color, alpha=alpha, edgecolor=(0,0,0,0))

plt.text(0.05, 0.95, "Generative Poster C", fontsize=18, weight='bold', transform=plt.gca().transAxes, color=(0.1,0.3,0.1))
plt.text(0.05, 0.91, "Greenish • Medium Layers", fontsize=11, transform=plt.gca().transAxes, color=(0.1,0.4,0.1))
plt.xlim(0,1); plt.ylim(0,1)
plt.show()

"""# Task4 - Minimal"""

import random, math
import numpy as np
import matplotlib.pyplot as plt

def minimal_palette(k=6):
    """Muted pastel colors"""
    colors = []
    for _ in range(k):
        r = random.uniform(0.7, 0.9)
        g = random.uniform(0.7, 0.9)
        b = random.uniform(0.7, 0.9)
        colors.append((r, g, b))
    return colors

def blob(center=(0.5, 0.5), r=0.3, points=200, wobble=0.05):
    angles = np.linspace(0, 2*math.pi, points)
    radii = r * (1 + wobble*(np.random.rand(points)-0.5))
    x = center[0] + radii * np.cos(angles)
    y = center[1] + radii * np.sin(angles)
    return x, y

# --- Minimal Poster ---
random.seed()
plt.figure(figsize=(7,10))
plt.axis('off')
plt.gca().set_facecolor((0.98,0.98,0.97))  # light neutral background

palette = minimal_palette(5)
n_layers = 3  # few layers
for i in range(n_layers):
    cx, cy = random.random(), random.random()
    rr = random.uniform(0.15, 0.3)
    x, y = blob(center=(cx, cy), r=rr, wobble=random.uniform(0.02,0.05))
    color = random.choice(palette)
    alpha = random.uniform(0.3,0.6)
    plt.fill(x, y, color=color, alpha=alpha, edgecolor=(0,0,0,0))

plt.text(0.05, 0.95, "Minimal Poster", fontsize=18, weight='bold', transform=plt.gca().transAxes)
plt.show()

"""# Task4 - Vivid"""

def vivid_palette():
    """High-contrast vivid colors (neon-like)"""
    return [
        (0.0, 1.0, 0.0),    # neon green
        (1.0, 0.0, 0.0),    # red
        (1.0, 1.0, 0.0),    # yellow
        (0.0, 1.0, 1.0),    # cyan
        (1.0, 0.0, 1.0)     # magenta
    ]

# --- Vivid Poster ---
random.seed()
plt.figure(figsize=(7,10))
plt.axis('off')
plt.gca().set_facecolor((0.0,0.0,0.0))  # black background

palette = vivid_palette()
n_layers = 20  # many layers
for i in range(n_layers):
    cx, cy = random.random(), random.random()
    rr = random.uniform(0.2, 0.6)
    x, y = blob(center=(cx, cy), r=rr, wobble=random.uniform(0.2,0.4))
    color = random.choice(palette)
    alpha = random.uniform(0.5,0.9)
    plt.fill(x, y, color=color, alpha=alpha, edgecolor=(0,0,0,0))

plt.text(0.05, 0.95, "Vivid Poster", fontsize=18, weight='bold', transform=plt.gca().transAxes, color=(1,1,1))
plt.show()

"""# Task4 - Noise Touch"""

def noisytouch_palette(k=6):
    """Soft but slightly saturated colors"""
    colors = []
    for _ in range(k):
        r = random.uniform(0.5, 0.9)
        g = random.uniform(0.5, 0.9)
        b = random.uniform(0.5, 0.9)
        colors.append((r, g, b))
    return colors

# --- NoiseTouch Poster ---
random.seed()
plt.figure(figsize=(7,10))
plt.axis('off')
plt.gca().set_facecolor((0.95,0.95,0.95))

palette = noisytouch_palette(6)
n_layers = 12  # medium layers
for i in range(n_layers):
    cx, cy = random.random(), random.random()
    rr = random.uniform(0.2, 0.5)
    x, y = blob(center=(cx, cy), r=rr, wobble=random.uniform(0.25,0.5))  # high wobble
    color = random.choice(palette)
    alpha = random.uniform(0.4,0.7)
    plt.fill(x, y, color=color, alpha=alpha, edgecolor=(0,0,0,0))

plt.text(0.05, 0.95, "NoiseTouch Poster", fontsize=18, weight='bold', transform=plt.gca().transAxes)
plt.show()

"""# Task5 - 1&2"""

# Generative Abstract Poster with seed
import random
import math
import numpy as np
import matplotlib.pyplot as plt

def random_palette(k=5):
    # return k random pastel-like colors
    return [(random.random(), random.random(), random.random()) for _ in range(k)]

def blob(center=(0.5, 0.5), r=0.3, points=200, wobble=0.15):
    # generate a wobbly closed shape
    angles = np.linspace(0, 2*math.pi, points)
    radii = r * (1 + wobble*(np.random.rand(points)-0.5))
    x = center[0] + radii * np.cos(angles)
    y = center[1] + radii * np.sin(angles)
    return x, y

# ---- Add seed here ----
seed = 42  # 원하는 숫자로 바꾸면 항상 같은 그림 생성
random.seed(seed)
np.random.seed(seed)  # numpy 난수도 동일하게 고정

plt.figure(figsize=(7,10))
plt.axis('off')

# background
plt.gca().set_facecolor((0.98,0.98,0.97))

palette = random_palette(6)
n_layers = 8
for i in range(n_layers):
    cx, cy = random.random(), random.random()
    rr = random.uniform(0.15, 0.45)
    x, y = blob(center=(cx, cy), r=rr, wobble=random.uniform(0.05,0.25))
    color = random.choice(palette)
    alpha = random.uniform(0.25, 0.6)
    plt.fill(x, y, color=color, alpha=alpha, edgecolor=(0,0,0,0))

# simple typographic label
plt.text(0.05, 0.95, "Generative Poster", fontsize=18, weight='bold', transform=plt.gca().transAxes)
plt.text(0.05, 0.91, "Week 2 • Arts & Advanced Big Data", fontsize=11, transform=plt.gca().transAxes)

plt.xlim(0,1); plt.ylim(0,1)
plt.show()

# Generative Abstract Poster with seed
import random
import math
import numpy as np
import matplotlib.pyplot as plt

def random_palette(k=5):
    # return k random pastel-like colors
    return [(random.random(), random.random(), random.random()) for _ in range(k)]

def blob(center=(0.5, 0.5), r=0.3, points=200, wobble=0.15):
    # generate a wobbly closed shape
    angles = np.linspace(0, 2*math.pi, points)
    radii = r * (1 + wobble*(np.random.rand(points)-0.5))
    x = center[0] + radii * np.cos(angles)
    y = center[1] + radii * np.sin(angles)
    return x, y

# ---- Add seed here ----
seed = 42  # 원하는 숫자로 바꾸면 항상 같은 그림 생성
random.seed(seed)
np.random.seed(seed)  # numpy 난수도 동일하게 고정

plt.figure(figsize=(7,10))
plt.axis('off')

# background
plt.gca().set_facecolor((0.98,0.98,0.97))

palette = random_palette(6)
n_layers = 8
for i in range(n_layers):
    cx, cy = random.random(), random.random()
    rr = random.uniform(0.15, 0.45)
    x, y = blob(center=(cx, cy), r=rr, wobble=random.uniform(0.05,0.25))
    color = random.choice(palette)
    alpha = random.uniform(0.25, 0.6)
    plt.fill(x, y, color=color, alpha=alpha, edgecolor=(0,0,0,0))

# simple typographic label
plt.text(0.05, 0.95, "Generative Poster", fontsize=18, weight='bold', transform=plt.gca().transAxes)
plt.text(0.05, 0.91, "Week 2 • Arts & Advanced Big Data", fontsize=11, transform=plt.gca().transAxes)

plt.xlim(0,1); plt.ylim(0,1)
plt.show()

"""# Task5 - 3&4"""

seed = 123
random.seed(seed)
np.random.seed(seed)

plt.figure(figsize=(7,10))
plt.axis('off')
plt.gca().set_facecolor((0.98,0.98,0.97))

palette = random_palette(6)
n_layers = 8
for i in range(n_layers):
    cx, cy = random.random(), random.random()
    rr = random.uniform(0.15, 0.45)
    x, y = blob(center=(cx, cy), r=rr, wobble=random.uniform(0.05,0.25))
    color = random.choice(palette)
    alpha = random.uniform(0.25, 0.6)
    plt.fill(x, y, color=color, alpha=alpha, edgecolor=(0,0,0,0))

plt.text(0.05, 0.95, "Generative Poster Seed 123", fontsize=18, weight='bold', transform=plt.gca().transAxes)
plt.text(0.05, 0.91, "Week 2 • Arts & Advanced Big Data", fontsize=11, transform=plt.gca().transAxes)

plt.xlim(0,1); plt.ylim(0,1)
plt.show()

seed = 987
random.seed(seed)
np.random.seed(seed)

plt.figure(figsize=(7,10))
plt.axis('off')
plt.gca().set_facecolor((0.98,0.98,0.97))

palette = random_palette(6)
n_layers = 8
for i in range(n_layers):
    cx, cy = random.random(), random.random()
    rr = random.uniform(0.15, 0.45)
    x, y = blob(center=(cx, cy), r=rr, wobble=random.uniform(0.05,0.25))
    color = random.choice(palette)
    alpha = random.uniform(0.25, 0.6)
    plt.fill(x, y, color=color, alpha=alpha, edgecolor=(0,0,0,0))

plt.text(0.05, 0.95, "Generative Poster Seed 987", fontsize=18, weight='bold', transform=plt.gca().transAxes)
plt.text(0.05, 0.91, "Week 2 • Arts & Advanced Big Data", fontsize=11, transform=plt.gca().transAxes)

plt.xlim(0,1); plt.ylim(0,1)
plt.show()

"""# Task6 - png file"""

seed = 42
random.seed(seed)
np.random.seed(seed)

plt.figure(figsize=(7,10))
plt.axis('off')
plt.gca().set_facecolor((0.98,0.98,0.97))

palette = random_palette(6)
n_layers = 8
for i in range(n_layers):
    cx, cy = random.random(), random.random()
    rr = random.uniform(0.15, 0.45)
    x, y = blob(center=(cx, cy), r=rr, wobble=random.uniform(0.05,0.25))
    color = random.choice(palette)
    alpha = random.uniform(0.25, 0.6)
    plt.fill(x, y, color=color, alpha=alpha, edgecolor=(0,0,0,0))

plt.text(0.05, 0.95, "Generative Poster", fontsize=18, weight='bold', transform=plt.gca().transAxes)
plt.text(0.05, 0.91, "Week 2 • Arts & Advanced Big Data", fontsize=11, transform=plt.gca().transAxes)

plt.xlim(0,1); plt.ylim(0,1)

# Save the poster as a high-resolution PNG
plt.savefig("poster1.png", dpi=300)

plt.show()